### ISSUE TITLE
Support Backbone.VirtualCollection

### ISSUE THREAD

**Issue by oosterholt** [backbone-paginator/backbone.paginator#272]
It would be nice if Backbone.PageableCollection can handle a [Backbone.VirtualCollection](https://github.com/p3drosola/Backbone.VirtualCollection).

**Comment by WRidder** [comment]
This is an issue I've been looking at as well (discussed here: https://github.com/p3drosola/Backbone.VirtualCollection/issues/58 as well). 

**Scenario**
```
				  +--------+   +------------+                  
				  |        |   | VirtualCol |                  
				  |        +---> (Filter#1) |                  
				  |        |   |            |                  
				  |        |   +------------+                  
				  |        |   +------------+    +------------+
	+----+---+    |        |   | VirtualCol |    |  Backgrid  |
	| Server |    |Backbone+---> (Filter#2) +----> (filtered) |
	|  API   +---->  coll  |   |            |    |  listing   |
	|        |    |        |   +------------+    +------------+
	+--------+    |        |   +------------+                  
				  |        |   | VirtualCol |                  
				  |        +---+ (Filter#3) |                  
				  |        |   |            |                  
				  +--------+   +------------+                  
``` 
A general backbone collection is used as a data-pool. Any number of subsets can spawn from this using filtered virtual collections. These VC's are available to our views and should for example be displayed in a pageable backgrid listing. We're using the *client* mode of backbone.paginator.

**Problem**
As of now it seems you can only use an array of models as input. If these models are extracted from the aforementioned virtual collection events on the pageable collection are not passed to the virtual collection. However, this is not necessarily an issue for virtual collections only.

I suppose the question merely is if it's possible to use a collection as input instead of just an array of models.

**Possible solutions**
*1*
The easiest solution right available right away is just tieing up the events between the source collection and pageable collection. This means listening for all relevant events on both collections and pass them to the other. While not elegant this does work and requires no changes to backbone.paginator.

*2*
If the presented scenario does indeed depict a valid use-case we may want to discuss the possibilities of using (virtual) collections as input to backbone.paginator. I suppose this would mean roughly the same approach as mentioned in *#1* but internally. 

Let me hear what you think.

**Comment by WRidder** [comment]
An example showing the (albeit obvious) issue has been setup here:

**Comment by WRidder** [comment]
Took a stab at a client-side only Backbone.Paginator fork which can handle collections as input: https://github.com/WRidder/Backbone.PaginationCollection.

**Comment by wyuenho** [comment]
I'm afraid this is too complex a use-case for pageable to support. The code that deals with syncing the backing collection and the pageable view is already ridiculously complex as it is. This is a larger issue with backbone not providing any obvious way to automatically sync change between collections. Again, these ORM calibre functionality really don't belong to the front-end.
