### ISSUE TITLE
Cannot use string for data

### ISSUE THREAD

**Issue by abzainuddin** [backbone-paginator/backbone.paginator#287]
With Backbone.Collection you can optionally set data when fetching a collection from the server as follows:

```
collection.fetch({data: {
    some: 'data'
}})
```

It is also possible to fetch using a string:

```
collection.fetch({data: 'some=string'})
```

But this does not work with Backbone.Paginator. I get the following error:

```
Uncaught TypeError: Cannot assign to read only property 'page' of some=string.
```

**Comment by wyuenho** [comment]
This isn't a supported use case since you can alway supply your KVP in object form. backbone.paginator itself needs to manipulate the `data` object to construct query string, otherwise backbone.paginator will have to provide a way for you to manipulate the query string directly. While it's not impossible, it'll just complicate things. If this is really crucial to you, a PR is welcome.

**Comment by daton89** [comment]
@abzainuddin 
in your controller: 
`const collection = new Collection{ select: 'name age' })`

in you model
`
	initialize(options) {
		this.url = this.url + '?' + $.param(options)
	},
`

**Comment by abzainuddin** [comment]
I completely forgot about this ticket, but thanks for giving an example @daton89
