### ISSUE TITLE
Current system does not allow for query string + body data for POST request

### ISSUE THREAD

**Issue by psdao1102** [backbone-paginator/backbone.paginator#300]
The fetch operation currently parses any query string parameters on the URL and sets them to the data object. So if i have options.type="POST"; the query string will be sent as part of the body. This gets even worse if you decide you want the body sent as JSON instead of forms data. 

What i need to do is have backbone.paginator JSON.stringify options.data before sending it to the server. Otherwise when paginator tries to set data from state, it will throw an error.

**Comment by wyuenho** [comment]
Internally, `options.data` will be kept as a plain JS hash both in backbone.paginator and backbone. It is only when it is about to be sent across the wire will backbone/jquery stringify it or serialize it into form data. See http://backbonejs.org/#Sync

**Comment by wyuenho** [comment]
I'm not sure what you are asking here really. Are you trying to fetch by using a issuing a request that will also *insert* into the DB? Are you asking me to exclude the pagination params from the body of a POST'ed fetch request? How do you want to sent the pagination params over then? If the params are going to be in your URL anyway, why don't you just use the default GET fetch requests? You either want to modify the DB or not, when you do, use POST, otherwise GET. You can filter out the pagination params on the server-side if you don't want them to persist.

**Comment by ludoo0d0a** [comment]
I wanted the same thing and achieve it by passing an extra parameter {postData: true} 

```js
fetch: function (options) {
...
      //Hack to keep object in data for a POST
      if (options.postData && options.data && _isObject(options.data)){
    	  options.data = JSON.stringify(options.data);
      }
      return BBColProto.fetch.call(this, options);
    },
```

Could it a be a solution ?

**Comment by wyuenho** [comment]
@ludoo0d0a that'll work

**Comment by ludoo0d0a** [comment]
Great, could it be included in the trunk ?

**Comment by wyuenho** [comment]
This is not a bug. It's a feature.

**Comment by ludoo0d0a** [comment]
yes, so could we expect to see this feature available ?
